import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const htmlPath = path.join(root, 'dist', 'index.html')
const outPath = path.resolve(root, '..', 'Views', 'AiChatHtml.g.cs')

let html = fs.readFileSync(htmlPath, 'utf8').replace(/\r\n/g, '\n')

const scripts = []
html = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, match => {
  scripts.push(match.replace(/\s+type="module"/gi, '').replace(/\s+crossorigin/gi, ''))
  return ''
})
if (scripts.length > 0) {
  html = html.replace('</body>', () => `${scripts.join('\n')}\n  </body>`)
}

const delimiter = '""""""""'
const source = `// <auto-generated />
namespace ZeroFall.AiPanel.Views;

internal static class AiChatHtmlTemplate
{
    public const string Value = ${delimiter}
${html}
${delimiter};
}
`

fs.writeFileSync(outPath, source, 'utf8')
