using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZeroFall.AiToolGen;

[Generator]
public class AiToolSourceGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toolClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetClassSymbol(ctx))
            .Where(static c => c is not null)
            .Select(static (c, _) => c!);

        context.RegisterSourceOutput(toolClasses, static (spc, classSymbol) =>
        {
            var generated = GenerateRegistration(classSymbol);
            if (generated == null) return;

            var hintName = $"{classSymbol.ContainingNamespace.ToDisplayString()}.{classSymbol.Name}".Replace('.', '_').Replace('+', '_') + ".g.cs";
            spc.AddSource(hintName, SourceText.From(generated, Encoding.UTF8));
        });
    }

    private static INamedTypeSymbol? GetClassSymbol(GeneratorSyntaxContext ctx)
    {
        var classDecl = ctx.Node as ClassDeclarationSyntax;
        if (classDecl == null) return null;

        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (classSymbol == null) return null;

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;
            foreach (var attr in method.GetAttributes())
            {
                if (attr.AttributeClass?.Name is "AiToolAttribute")
                    return classSymbol;
            }
        }

        return null;
    }

    private static string GetTypeDisplayName(ITypeSymbol type) => type.ToDisplayString(TypeFormat);

    private static bool IsListStringType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named) return false;
        if (named.ConstructedFrom is not { Name: "List" } generic) return false;
        if (generic.ContainingNamespace.ToDisplayString() != "System.Collections.Generic") return false;
        if (named.TypeArguments.Length != 1) return false;
        return named.TypeArguments[0].SpecialType == SpecialType.System_String;
    }

    private static string? GenerateRegistration(INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;
        var generatedClassName = $"AiToolRegistration_{className}";

        var methods = new List<(string Name, string Description, IMethodSymbol Method)>();

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;
            if (method.DeclaredAccessibility != Accessibility.Public) continue;
            if (method.MethodKind != MethodKind.Ordinary) continue;

            foreach (var attr in method.GetAttributes())
            {
                if (attr.AttributeClass?.Name is not "AiToolAttribute") continue;
                if (attr.ConstructorArguments.Length < 2) continue;

                var name = attr.ConstructorArguments[0].Value as string ?? method.Name;
                var description = attr.ConstructorArguments[1].Value as string ?? "";
                methods.Add((name, description, method));
                break;
            }
        }

        if (methods.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroFall.Base.AiTools;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public static class {generatedClassName}");
        sb.AppendLine("{");

        sb.AppendLine("    public static void Register(AiToolRegistry registry, IServiceProvider serviceProvider)");
        sb.AppendLine("    {");

        foreach (var (toolName, toolDesc, method) in methods)
        {
            var paramDefs = BuildParamDefinitions(method);
            var executor = BuildExecutor(ns, className, toolName, method);

            sb.AppendLine($"        registry.Register(\"{toolName}\", {executor}, new ToolDefinition");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = \"{toolName}\",");
            sb.AppendLine($"            Description = @\"{EscapeForVerbatim(toolDesc)}\",");
            sb.AppendLine("            Parameters =");
            sb.AppendLine("            [");
            foreach (var pd in paramDefs)
            {
                sb.AppendLine("                new ToolParameterDefinition");
                sb.AppendLine("                {");
                sb.AppendLine($"                    Name = \"{pd.Name}\",");
                sb.AppendLine($"                    Type = \"{pd.JsonSchemaType}\",");
                sb.AppendLine($"                    Description = @\"{EscapeForVerbatim(pd.Description)}\",");
                sb.AppendLine($"                    Required = {pd.Required.ToString().ToLowerInvariant()}");
                sb.AppendLine("                },");
            }
            sb.AppendLine("            ]");
            sb.AppendLine("        });");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static List<(string Name, string JsonSchemaType, string Description, bool Required)> BuildParamDefinitions(IMethodSymbol method)
    {
        var result = new List<(string, string, string, bool)>();

        foreach (var param in method.Parameters)
        {
            var name = param.Name;
            var description = "";
            var required = true;

            foreach (var attr in param.GetAttributes())
            {
                if (attr.AttributeClass?.Name is not "ToolParamAttribute") continue;
                if (attr.ConstructorArguments.Length >= 1)
                    description = attr.ConstructorArguments[0].Value as string ?? "";
                foreach (var named in attr.NamedArguments)
                {
                    if (named.Key == "Required" && named.Value.Value is bool r)
                        required = r;
                }
            }

            if (param.HasExplicitDefaultValue)
                required = false;

            var jsonType = MapTypeToJsonSchema(param.Type);
            result.Add((name, jsonType, description, required));
        }

        return result;
    }

    private static string MapTypeToJsonSchema(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_String) return "string";
        if (type.SpecialType == SpecialType.System_Boolean) return "boolean";
        if (type.SpecialType is SpecialType.System_Int32 or SpecialType.System_Int64) return "integer";
        if (type.SpecialType is SpecialType.System_Double or SpecialType.System_Single or SpecialType.System_Decimal) return "number";
        if (type.TypeKind == TypeKind.Enum) return "string";
        if (IsListStringType(type)) return "array";

        return "string";
    }

    private static string BuildExecutor(string ns, string className, string toolName, IMethodSymbol method)
    {
        var returnType = GetTypeDisplayName(method.ReturnType);
        var isAsync = method.ReturnType is INamedTypeSymbol { Name: "Task" or "ValueTask" } rt
            && rt.ContainingNamespace.ToDisplayString() == "System.Threading.Tasks";

        var paramBindings = new List<string>();
        foreach (var param in method.Parameters)
        {
            var paramName = param.Name;
            var paramType = GetTypeDisplayName(param.Type);
            var hasDefault = param.HasExplicitDefaultValue;
            var defaultExpr = hasDefault ? GetDefaultExpression(param.ExplicitDefaultValue, param.Type) : null;

            if (param.Type.TypeKind == TypeKind.Enum)
            {
                var enumType = GetTypeDisplayName(param.Type);
                paramBindings.Add($"var {paramName}_raw = args.TryGetString(\"{paramName}\", out var {paramName}_str) ? {paramName}_str : {(hasDefault ? $"\"{param.ExplicitDefaultValue}\"" : "null")};");
                paramBindings.Add($"var {paramName} = {paramName}_raw != null ? ({enumType})System.Enum.Parse(typeof({enumType}), {paramName}_raw) : ({enumType}){defaultExpr ?? $"default({enumType})"};");
            }
            else if (IsListStringType(param.Type))
            {
                var defaultVal = defaultExpr ?? "null";
                paramBindings.Add($"var {paramName} = args.TryGetStringList(\"{paramName}\", out var {paramName}_list) ? {paramName}_list : {defaultVal};");
            }
            else
            {
                var tryParseMethod = GetTryParseMethod(param.Type);
                if (tryParseMethod != null)
                {
                    var outVar = $"{paramName}_val";
                    var defaultVal = defaultExpr ?? GetDefaultValueLiteral(param.Type);
                    paramBindings.Add($"var {paramName} = args.{tryParseMethod}(\"{paramName}\", out var {outVar}) ? {outVar} : {defaultVal};");
                }
                else
                {
                    var defaultVal = defaultExpr ?? GetDefaultValueLiteral(param.Type);
                    paramBindings.Add($"var {paramName} = args.TryGetString(\"{paramName}\", out var {paramName}_s) ? {paramName}_s : {defaultVal};");
                }
            }
        }

        var paramList = string.Join(", ", method.Parameters.Select(p => p.Name));
        var callExpr = $"svc.{method.Name}({paramList})";

        var sb = new StringBuilder();
        sb.AppendLine("async (args) =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var svc = serviceProvider.GetRequiredService<{ns}.{className}>();");

        foreach (var binding in paramBindings)
        {
            sb.AppendLine($"            {binding}");
        }

        sb.AppendLine();

        if (!isAsync)
        {
            if (method.ReturnType.ToDisplayString(TypeFormat) == "ZeroFall.Base.AiTools.ToolCallResult")
            {
                sb.AppendLine($"            return {callExpr};");
            }
            else
            {
                sb.AppendLine($"            var result = {callExpr};");
                sb.AppendLine($"            return new ToolCallResult(result?.ToString() ?? \"\", \"{toolName}\");");
            }
        }
        else
        {
            var taskInnerType = (method.ReturnType as INamedTypeSymbol)?.TypeArguments.FirstOrDefault();
            if (taskInnerType == null)
            {
                sb.AppendLine($"            await {callExpr};");
                sb.AppendLine($"            return new ToolCallResult(\"\", \"{toolName}\");");
            }
            else
            {
                var innerName = GetTypeDisplayName(taskInnerType);
                if (innerName == "ZeroFall.Base.AiTools.ToolCallResult")
                {
                    sb.AppendLine($"            return await {callExpr};");
                }
                else if (taskInnerType.SpecialType == SpecialType.System_String)
                {
                    sb.AppendLine($"            var result = await {callExpr};");
                    sb.AppendLine($"            return new ToolCallResult(result ?? \"\", \"{toolName}\");");
                }
                else
                {
                    sb.AppendLine($"            var result = await {callExpr};");
                    sb.AppendLine($"            return new ToolCallResult(result?.ToString() ?? \"\", \"{toolName}\");");
                }
            }
        }

        sb.Append("        }");

        return sb.ToString();
    }

    private static string? GetTryParseMethod(ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_Int32 => "TryGetInt32",
            SpecialType.System_Int64 => "TryGetInt64",
            SpecialType.System_Double => "TryGetDouble",
            SpecialType.System_Boolean => "TryGetBoolean",
            SpecialType.System_Single => "TryGetSingle",
            SpecialType.System_Decimal => "TryGetDecimal",
            _ => null
        };
    }

    private static string GetDefaultValueLiteral(ITypeSymbol type)
    {
        return type.SpecialType switch
        {
            SpecialType.System_String => "null",
            SpecialType.System_Int32 => "0",
            SpecialType.System_Int64 => "0L",
            SpecialType.System_Double => "0.0",
            SpecialType.System_Single => "0.0f",
            SpecialType.System_Decimal => "0.0m",
            SpecialType.System_Boolean => "false",
            _ => $"default({GetTypeDisplayName(type)})"
        };
    }

    private static string? GetDefaultExpression(object? defaultValue, ITypeSymbol type)
    {
        if (defaultValue == null) return "null";
        return type.SpecialType switch
        {
            SpecialType.System_String => $"\"{defaultValue}\"",
            SpecialType.System_Boolean => defaultValue.ToString()?.ToLowerInvariant() ?? "false",
            SpecialType.System_Int32 => defaultValue.ToString() ?? "0",
            SpecialType.System_Int64 => defaultValue.ToString() + "L",
            SpecialType.System_Double => defaultValue.ToString() ?? "0.0",
            SpecialType.System_Single => defaultValue.ToString() + "f",
            SpecialType.System_Decimal => defaultValue.ToString() + "m",
            _ => $"default({GetTypeDisplayName(type)})"
        };
    }

    private static string EscapeForVerbatim(string s)
    {
        return s.Replace("\"", "\"\"");
    }
}
